In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [3]:
house=pd.read_csv('House_Price_dataset.csv')

In [4]:
house.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent,Area Type,Area Size,Area Category
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,4 Marla,For Sale,2,02-04-2019,NaN,NaN,Marla,4.0,0-5 Marla
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,5.6 Marla,For Sale,3,05-04-2019,NaN,NaN,Marla,5.6,5-10 Marla
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,8 Marla,For Sale,5,07-17-2019,NaN,NaN,Marla,8.0,5-10 Marla
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,2 Kanal,For Sale,4,04-05-2019,NaN,NaN,Kanal,2.0,1-5 Kanal
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,8 Marla,For Sale,3,07-10-2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,Marla,8.0,5-10 Marla

In [5]:
house.isnull().sum()

property_id          0
location_id          0
page_url             0
property_type        0
price                0
location             0
city                 0
province_name        0
latitude             0
longitude            0
baths                0
area                 0
purpose              0
bedrooms             0
date_added           0
agency           44071
agent            44072
Area Type            0
Area Size            0
Area Category        0
dtype: int64

In [6]:
house.groupby('Area Type')['Area Type'].agg('count')

Area Type
Kanal     30677
Marla    137769
Name: Area Type, dtype: int64

In [7]:
house['Area_in_Marla'] = house.apply(
    lambda x: x['Area Size'] * 20 if x['Area Type'].lower() == 'kanal' else x['Area Size'],
    axis=1
)

In [8]:
house.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,...,area,purpose,bedrooms,date_added,agency,agent,Area Type,Area Size,Area Category,Area_in_Marla
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,...,4 Marla,For Sale,2,02-04-2019,NaN,NaN,Marla,4.0,0-5 Marla,4.0
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,...,5.6 Marla,For Sale,3,05-04-2019,NaN,NaN,Marla,5.6,5-10 Marla,5.6
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,...,8 Marla,For Sale,5,07-17-2019,NaN,NaN,Marla,8.0,5-10 Marla,8.0
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,...,2 Kanal,For Sale,4,04-05-2019,NaN,NaN,Kanal,2.0,1-5 Kanal,40.0
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,...,8 Marla,For Sale,3,07-10-2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,Marla,8.0,5-10 Marla,8.0

In [9]:
house = house.drop(['property_id', 'location_id', 'page_url', 'agent', 'agency','Area Type','Area Size','Area Category','area','longitude','latitude','province_name','date_added'], axis=1)

In [10]:
house.head()

,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0

In [11]:
house.isnull().sum()

property_type    0
price            0
location         0
city             0
baths            0
purpose          0
bedrooms         0
Area_in_Marla    0
dtype: int64

In [12]:
house.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
168441     True
168442     True
168443     True
168444    False
168445     True
Length: 168446, dtype: bool

In [13]:
house.shape

(168446, 8)

In [14]:
house.head()

,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0

In [15]:
house = house[(house['price'] > 1e5) & (house['price'] < 2e8)]

In [16]:
y = np.log1p(house['price'])

In [17]:
X = house[['property_type','location','city','baths','purpose','bedrooms','Area_in_Marla']]

In [18]:
X = pd.get_dummies(X, columns=['property_type','location','city','purpose'],dtype=int)

In [19]:
house.isnull().sum()

property_type    0
price            0
location         0
city             0
baths            0
purpose          0
bedrooms         0
Area_in_Marla    0
dtype: int64

In [20]:
house.shape

(129566, 8)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [22]:
X

,baths,bedrooms,Area_in_Marla,property_type_Farm House,property_type_Flat,property_type_House,property_type_Lower Portion,property_type_Penthouse,property_type_Room,property_type_Upper Portion,...,location_Zubair Colony,location_Zulfiqar Colony,location_circular road,city_Faisalabad,city_Islamabad,city_Karachi,city_Lahore,city_Rawalpindi,purpose_For Rent,purpose_For Sale
0,2,2,4.0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,3,3,5.6,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,6,5,8.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,4,4,40.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,3,3,8.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168441,0,6,9.6,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
168442,0,3,8.0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
168443,0,6,9.6,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
168444,0,3,7.8,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
168445,3,3,9.4,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [23]:
y

0         16.118096
1         15.747032
2         16.618871
3         17.588272
4         15.761421
            ...
168441    17.092655
168442    16.341239
168443    17.111347
168444    16.213406
168445    16.012735
Name: price, Length: 129566, dtype: float64

In [24]:
X_train

,baths,bedrooms,Area_in_Marla,property_type_Farm House,property_type_Flat,property_type_House,property_type_Lower Portion,property_type_Penthouse,property_type_Room,property_type_Upper Portion,...,location_Zubair Colony,location_Zulfiqar Colony,location_circular road,city_Faisalabad,city_Islamabad,city_Karachi,city_Lahore,city_Rawalpindi,purpose_For Rent,purpose_For Sale
82109,5,4,10.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
93552,5,4,10.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
49433,10,9,48.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
15642,4,7,40.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
114411,6,5,10.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166447,3,3,8.6,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
132753,0,0,12.0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
1019,2,2,5.7,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
19581,3,3,8.0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
158027,4,3,5.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [24]:
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [25]:
y_pred_log = rf.predict(X_test)
y_pred = np.expm1(y_pred_log)

In [26]:
y_pred

array([1.96205957e+07, 7.78507398e+06, 1.44676480e+07, ...,
       1.43208190e+08, 2.31778629e+07, 1.12289649e+07], shape=(25914,))

In [27]:
rmse = np.sqrt(mean_squared_error(np.expm1(y_test), y_pred))
print("RMSE:", rmse)

RMSE: 8634370.66171792

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

y_pred_log = rf.predict(X_test)
rmse_log = np.sqrt(mean_squared_error(y_test, y_pred_log))

y_pred = np.expm1(y_pred_log)
y_test_exp = np.expm1(y_test)


rmse_pkr = np.sqrt(mean_squared_error(y_test_exp, y_pred))
mape = mean_absolute_percentage_error(y_test_exp, y_pred) * 100

print("Log-RMSE:", rmse_log)
print("RMSE (PKR):", rmse_pkr)
print("MAPE (%):", mape)

Log-RMSE: 0.29408387905968475
RMSE (PKR): 8634370.66171792
MAPE (%): 25.662896698715066

In [26]:
import pickle

In [33]:
with open("RandomForest.pkl", "wb") as f:
    pickle.dump(rf, f)

In [27]:
with open("training_columns.pkl", "wb") as f:
    pickle.dump(X_train.columns.tolist(), f)